language: python
python:
  - 3.5
  - 3.8
env:
  - DJANGO=">=2.2,<3.0"
  - DJANGO=">=3.0,<3.1"
  - DJANGO=">=3.1,<3.2"
before_install:
  - export DJANGO_SETTINGS_MODULE=jet.tests.settings
install:
  - pip install -q "Django${DJANGO}"
  - pip install .
  - pip install coverage
  - pip install coveralls
script:
  - coverage run --source=jet manage.py test jet
after_success:
  - coverage report
  - coveralls
matrix:
  exclude:
    - python: 3.5
      env: DJANGO=">=3.0,<3.1"
    - python: 3.5
      env: DJANGO=">=3.1,<3.2"
